# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- production

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install @angular/cli-g'

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run-script build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'dist'
    publishLocation: 'FilePath'
    TargetPath: 'Visual Studio Team Service/TFS'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Azure(030bf431-99c0-479e-8f62-bf5dfefb9877)'
    appType: 'webApp'
    WebAppName: 'commerce-kai-web-admin'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist/KoperasiAstra'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
  


